/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IPerpProtocolInterface extends Interface {
  getFunction(
    nameOrSignature: "closePosition" | "openPosition"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "closePosition",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "openPosition",
    values: [boolean, BigNumberish, BigNumberish, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "closePosition",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openPosition",
    data: BytesLike
  ): Result;
}

export interface IPerpProtocol extends BaseContract {
  connect(runner?: ContractRunner | null): IPerpProtocol;
  waitForDeployment(): Promise<this>;

  interface: IPerpProtocolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  closePosition: TypedContractMethod<
    [positionId: BytesLike],
    [bigint],
    "nonpayable"
  >;

  openPosition: TypedContractMethod<
    [
      isLong: boolean,
      size: BigNumberish,
      leverage: BigNumberish,
      collateral: AddressLike,
      collateralAmount: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "closePosition"
  ): TypedContractMethod<[positionId: BytesLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "openPosition"
  ): TypedContractMethod<
    [
      isLong: boolean,
      size: BigNumberish,
      leverage: BigNumberish,
      collateral: AddressLike,
      collateralAmount: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  filters: {};
}
