/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPerpProtocol,
  IPerpProtocolInterface,
} from "../../MoixaExecutor.sol/IPerpProtocol";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "positionId",
        type: "bytes32",
      },
    ],
    name: "closePosition",
    outputs: [
      {
        internalType: "int256",
        name: "pnl",
        type: "int256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "isLong",
        type: "bool",
      },
      {
        internalType: "uint256",
        name: "size",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "leverage",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "collateral",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "collateralAmount",
        type: "uint256",
      },
    ],
    name: "openPosition",
    outputs: [
      {
        internalType: "bytes32",
        name: "positionId",
        type: "bytes32",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IPerpProtocol__factory {
  static readonly abi = _abi;
  static createInterface(): IPerpProtocolInterface {
    return new Interface(_abi) as IPerpProtocolInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPerpProtocol {
    return new Contract(address, _abi, runner) as unknown as IPerpProtocol;
  }
}
