allowBuilds:
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  bufferutil: set this to true or false
  keccak: set this to true or false
  prisma: set this to true or false
  secp256k1: set this to true or false
  unrs-resolver: set this to true or false
  utf-8-validate: set this to true or false
