/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace MoixaBrain {
  export type DecisionStruct = {
    timestamp: BigNumberish;
    marketContext: string;
    signalDetected: string;
    confidenceScore: BigNumberish;
    tradeDirection: string;
    token: string;
    positionSize: BigNumberish;
    riskLevel: string;
    riskReasoning: string;
    expectedReturn: BigNumberish;
    actualReturn: BigNumberish;
    wasCorrect: boolean;
    isClosed: boolean;
    learningNote: string;
  };

  export type DecisionStructOutput = [
    timestamp: bigint,
    marketContext: string,
    signalDetected: string,
    confidenceScore: bigint,
    tradeDirection: string,
    token: string,
    positionSize: bigint,
    riskLevel: string,
    riskReasoning: string,
    expectedReturn: bigint,
    actualReturn: bigint,
    wasCorrect: boolean,
    isClosed: boolean,
    learningNote: string
  ] & {
    timestamp: bigint;
    marketContext: string;
    signalDetected: string;
    confidenceScore: bigint;
    tradeDirection: string;
    token: string;
    positionSize: bigint;
    riskLevel: string;
    riskReasoning: string;
    expectedReturn: bigint;
    actualReturn: bigint;
    wasCorrect: boolean;
    isClosed: boolean;
    learningNote: string;
  };
}

export interface MoixaBrainInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "closeDecision"
      | "correctDecisions"
      | "decisions"
      | "getAccuracy"
      | "getDecision"
      | "getRecentDecisions"
      | "getTotalStats"
      | "moixaAgent"
      | "owner"
      | "recordDecision"
      | "setMoixaAgent"
      | "totalDecisions"
      | "totalVolume"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentUpdated"
      | "DecisionClosed"
      | "DecisionRecorded"
      | "MoixaLearned"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "closeDecision",
    values: [BigNumberish, BigNumberish, boolean, string]
  ): string;
  encodeFunctionData(
    functionFragment: "correctDecisions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "decisions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAccuracy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDecision",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecentDecisions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalStats",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "moixaAgent",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordDecision",
    values: [
      string,
      string,
      BigNumberish,
      string,
      string,
      BigNumberish,
      string,
      string,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setMoixaAgent",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalDecisions",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalVolume",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "closeDecision",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "correctDecisions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decisions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAccuracy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDecision",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecentDecisions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "moixaAgent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordDecision",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMoixaAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalDecisions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalVolume",
    data: BytesLike
  ): Result;
}

export namespace AgentUpdatedEvent {
  export type InputTuple = [newAgent: AddressLike];
  export type OutputTuple = [newAgent: string];
  export interface OutputObject {
    newAgent: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DecisionClosedEvent {
  export type InputTuple = [
    id: BigNumberish,
    actualReturn: BigNumberish,
    wasCorrect: boolean
  ];
  export type OutputTuple = [
    id: bigint,
    actualReturn: bigint,
    wasCorrect: boolean
  ];
  export interface OutputObject {
    id: bigint;
    actualReturn: bigint;
    wasCorrect: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DecisionRecordedEvent {
  export type InputTuple = [
    id: BigNumberish,
    token: string,
    direction: string,
    confidence: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    token: string,
    direction: string,
    confidence: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    id: bigint;
    token: string;
    direction: string;
    confidence: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MoixaLearnedEvent {
  export type InputTuple = [id: BigNumberish, note: string];
  export type OutputTuple = [id: bigint, note: string];
  export interface OutputObject {
    id: bigint;
    note: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MoixaBrain extends BaseContract {
  connect(runner?: ContractRunner | null): MoixaBrain;
  waitForDeployment(): Promise<this>;

  interface: MoixaBrainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  closeDecision: TypedContractMethod<
    [
      decisionId: BigNumberish,
      actualReturn: BigNumberish,
      wasCorrect: boolean,
      learningNote: string
    ],
    [void],
    "nonpayable"
  >;

  correctDecisions: TypedContractMethod<[], [bigint], "view">;

  decisions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        string
      ] & {
        timestamp: bigint;
        marketContext: string;
        signalDetected: string;
        confidenceScore: bigint;
        tradeDirection: string;
        token: string;
        positionSize: bigint;
        riskLevel: string;
        riskReasoning: string;
        expectedReturn: bigint;
        actualReturn: bigint;
        wasCorrect: boolean;
        isClosed: boolean;
        learningNote: string;
      }
    ],
    "view"
  >;

  getAccuracy: TypedContractMethod<[], [bigint], "view">;

  getDecision: TypedContractMethod<
    [id: BigNumberish],
    [MoixaBrain.DecisionStructOutput],
    "view"
  >;

  getRecentDecisions: TypedContractMethod<
    [count: BigNumberish],
    [MoixaBrain.DecisionStructOutput[]],
    "view"
  >;

  getTotalStats: TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        total: bigint;
        correct: bigint;
        accuracy: bigint;
        volume: bigint;
      }
    ],
    "view"
  >;

  moixaAgent: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  recordDecision: TypedContractMethod<
    [
      marketContext: string,
      signalDetected: string,
      confidenceScore: BigNumberish,
      tradeDirection: string,
      token: string,
      positionSize: BigNumberish,
      riskLevel: string,
      riskReasoning: string,
      expectedReturn: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  setMoixaAgent: TypedContractMethod<
    [_agent: AddressLike],
    [void],
    "nonpayable"
  >;

  totalDecisions: TypedContractMethod<[], [bigint], "view">;

  totalVolume: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "closeDecision"
  ): TypedContractMethod<
    [
      decisionId: BigNumberish,
      actualReturn: BigNumberish,
      wasCorrect: boolean,
      learningNote: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "correctDecisions"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "decisions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        string,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        string
      ] & {
        timestamp: bigint;
        marketContext: string;
        signalDetected: string;
        confidenceScore: bigint;
        tradeDirection: string;
        token: string;
        positionSize: bigint;
        riskLevel: string;
        riskReasoning: string;
        expectedReturn: bigint;
        actualReturn: bigint;
        wasCorrect: boolean;
        isClosed: boolean;
        learningNote: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAccuracy"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDecision"
  ): TypedContractMethod<
    [id: BigNumberish],
    [MoixaBrain.DecisionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRecentDecisions"
  ): TypedContractMethod<
    [count: BigNumberish],
    [MoixaBrain.DecisionStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getTotalStats"
  ): TypedContractMethod<
    [],
    [
      [bigint, bigint, bigint, bigint] & {
        total: bigint;
        correct: bigint;
        accuracy: bigint;
        volume: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "moixaAgent"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordDecision"
  ): TypedContractMethod<
    [
      marketContext: string,
      signalDetected: string,
      confidenceScore: BigNumberish,
      tradeDirection: string,
      token: string,
      positionSize: BigNumberish,
      riskLevel: string,
      riskReasoning: string,
      expectedReturn: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMoixaAgent"
  ): TypedContractMethod<[_agent: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalDecisions"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalVolume"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "AgentUpdated"
  ): TypedContractEvent<
    AgentUpdatedEvent.InputTuple,
    AgentUpdatedEvent.OutputTuple,
    AgentUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DecisionClosed"
  ): TypedContractEvent<
    DecisionClosedEvent.InputTuple,
    DecisionClosedEvent.OutputTuple,
    DecisionClosedEvent.OutputObject
  >;
  getEvent(
    key: "DecisionRecorded"
  ): TypedContractEvent<
    DecisionRecordedEvent.InputTuple,
    DecisionRecordedEvent.OutputTuple,
    DecisionRecordedEvent.OutputObject
  >;
  getEvent(
    key: "MoixaLearned"
  ): TypedContractEvent<
    MoixaLearnedEvent.InputTuple,
    MoixaLearnedEvent.OutputTuple,
    MoixaLearnedEvent.OutputObject
  >;

  filters: {
    "AgentUpdated(address)": TypedContractEvent<
      AgentUpdatedEvent.InputTuple,
      AgentUpdatedEvent.OutputTuple,
      AgentUpdatedEvent.OutputObject
    >;
    AgentUpdated: TypedContractEvent<
      AgentUpdatedEvent.InputTuple,
      AgentUpdatedEvent.OutputTuple,
      AgentUpdatedEvent.OutputObject
    >;

    "DecisionClosed(uint256,int256,bool)": TypedContractEvent<
      DecisionClosedEvent.InputTuple,
      DecisionClosedEvent.OutputTuple,
      DecisionClosedEvent.OutputObject
    >;
    DecisionClosed: TypedContractEvent<
      DecisionClosedEvent.InputTuple,
      DecisionClosedEvent.OutputTuple,
      DecisionClosedEvent.OutputObject
    >;

    "DecisionRecorded(uint256,string,string,uint256,uint256)": TypedContractEvent<
      DecisionRecordedEvent.InputTuple,
      DecisionRecordedEvent.OutputTuple,
      DecisionRecordedEvent.OutputObject
    >;
    DecisionRecorded: TypedContractEvent<
      DecisionRecordedEvent.InputTuple,
      DecisionRecordedEvent.OutputTuple,
      DecisionRecordedEvent.OutputObject
    >;

    "MoixaLearned(uint256,string)": TypedContractEvent<
      MoixaLearnedEvent.InputTuple,
      MoixaLearnedEvent.OutputTuple,
      MoixaLearnedEvent.OutputObject
    >;
    MoixaLearned: TypedContractEvent<
      MoixaLearnedEvent.InputTuple,
      MoixaLearnedEvent.OutputTuple,
      MoixaLearnedEvent.OutputObject
    >;
  };
}
